- name: Install UFW
  hosts: all
  gather_facts: false
  roles:
    - ufw

- name: Enable access over SSH
  hosts: all
  gather_facts: false
  roles:
    - ssh

- name: Enable unattended upgrades
  hosts: all
  gather_facts: false
  roles:
    - unattended_upgrades
